### ISSUE TITLE
Unable to agree to Terms of Use Agreement if accessing mariejs for the first time through a file link

### ISSUE THREAD

**Issue by creme332** [MARIE-js/MARIE.js#327]
If you try to open a MARIE js file through its link in incognito tab, you will not be able to accept the Terms of Use Agreement.

## Steps to reproduce
- Copy the link to some source file by clicking `File` > `Copy Link`. For example, the copied link to the Addition example is [this](https://marie.js.org/#code=/%20Addition%20Calculator%0A/%20by%20the%20MARIE.js%20Team%0A/%20Copyright%20(C)%202016.%20Licensed%20under%20the%20MIT%20License%0A%0AInput%0AStore%20X%0AInput%20%0AStore%20Y%0A%0AAdd%20X%0AOutput%0AHalt%0A%0AX,%20DEC%200%0AY,%20DEC%200).
- Open this link in an incognito tab.
- The screen should look like this: 
![image](https://github.com/MARIE-js/MARIE.js/assets/65414576/81825aa1-30bb-42c0-9820-0339e1664a2d)
- First click on `End tour` in the top left corner.
- Now try clicking on `I agree`. It will not work.

In the console log, the following error arises:
```
marie.min.js:13 Uncaught TypeError: Cannot read properties of undefined (reading 'setValue')
    at J (marie.min.js:13:10128)
    at f (marie.min.js:12:31741)
    at e (marie.min.js:12:31723)
    at marie.min.js:13:12467
```
## Note
- This problem does not arise if you first go to marie.js.org, accept the agreement, and then access the link to the code.
- I am using a Chrome browser (115.0.5790.171 (Official Build) (64-bit) (cohort: Stable)) on Windows 10.

**Comment by auroranil** [comment]
We have released MARIE.js v2.0 which removes the terms of use agreement popup message.

**Comment by creme332** [comment]
Thank you for your work. The problem now seems to be gone.
